INSERT INTO movies VALUES(1, 'The Incredibles', 'Brad Bird', 2004, 8.0);
INSERT INTO movies VALUES(2, '12th Fail', 'Vidhu Vinod Chopra', 2023, 9.1);
INSERT INTO movies VALUES(3, 'The Godfather', 'Francis Ford Coppola', 1972, 9.2);
INSERT INTO movies VALUES(4, 'How to Train Your Dragon', 'Dean DeBlois', 2010, 8.1);
INSERT INTO movies VALUES(5, 'Forrest Gump', 'Robert Zemeckis', 1994, 8.8);
INSERT INTO movies VALUES(6, 'Interstellar', 'Christopher Nolan', 2014, 8.7);
INSERT INTO movies VALUES(7, 'Batman Begins', 'Christopher Nolan', 2005, 8.2);
INSERT INTO movies VALUES(8, 'Joker', 'Todd Phillips', 2019, 8.4);
INSERT INTO movies VALUES(9, 'Oppenheimer', 'Christopher Nolan', 2023, 8.4);
INSERT INTO movies VALUES(10, 'Spider-Man: Across the Spider-Verse', 'Joaquim Dos Santos', 2023, 8.6);
INSERT INTO movies VALUES(11, 'Hamilton', 'Thomas Kail', 2020, 8.3);
INSERT INTO movies VALUES(12, 'Parasite', 'Bong Joon Ho', 2019, 8.5);
INSERT INTO movies VALUES(13, 'Avengers: EndGame', 'Anthony Russo', 2019, 8.4);
INSERT INTO movies VALUES(14, 'Logan', 'James Mangold', 2017, 8.1);
INSERT INTO movies VALUES(15, 'Inside Out', 'Pete Docter', 2015, 8.1);
INSERT INTO movies VALUES(16, 'The Wolf of Wall Street', 'Martin Scorsese', 2013, 8.2);
INSERT INTO movies VALUES(17, 'Star Wars: Episode V - The Empire Strikes Back', 'Irvin Kershner', 1980, 8.7);
INSERT INTO movies VALUES(18, 'Aladdin', 'Ron Clements', 1992, 8.0);
INSERT INTO movies VALUES(19, 'Groundhog Day', 'Harold Ramis', 1993, 8.0);
INSERT INTO movies VALUES(20, 'The Wizard of Oz', 'Victor Fleming', 1939, 8.1);
INSERT INTO movies VALUES(21, 'Hotel Rwanda', 'Terry George', 2004, 8.1);
INSERT INTO movies VALUES(22, 'Pirates of the Caribbean: The Curse of the Black Pearl', 'Gore Verbinski', 2003, 8.1);
INSERT INTO movies VALUES(23, 'Finding Nemo', 'Andrew Stanton', 2003, 8.2);
INSERT INTO movies VALUES(24, 'The Truman Show', 'Peter Weir', 1998, 8.2);
INSERT INTO movies VALUES(25, 'Toy Story', 'John Lasseter', 1995, 8.3);
INSERT INTO movies VALUES(26, 'The Shawshank Redemption', 'Frank Darabont', 1994, 9.3);
INSERT INTO movies VALUES(27, 'The Dark Knight', 'Christopher Nolan', 2008, 9.0);
INSERT INTO movies VALUES(28, 'The Godfather Part II', 'Francis Ford Coppola', 1974, 9.0);
INSERT INTO movies VALUES(29, 'Pulp Fiction', 'Quentin Tarantino', 1994, 8.9);
INSERT INTO movies VALUES(30, 'The Good, the Bad and the Ugly', 'Clint Eastwood', 1966, 8.8);
INSERT INTO movies VALUES(31, 'Seven Samurai', 'Akira Kurosawa', 1954, 8.6);
INSERT INTO movies VALUES(32, 'Its a Wonderful Life', 'Frank Capra', 1946, 8.6);
INSERT INTO movies VALUES(33, 'Poor Things', 'Yorgos Lanthimos', 2023, 8.4);
INSERT INTO movies VALUES(34, 'Jai Bhim', 'T.J. Gnanavel', 2021, 8.7);
INSERT INTO movies VALUES(35, 'The Intouchables', 'Olivier Nakache', 2011, 8.5);